<Vaccination>:
    name: "vaccination"

    MDBottomNavigation:
        panel_color: "#2e8b2e"

        MDBottomNavigationItem:
            name: "menu"
            text: "Menu"
            font_name: "fonts/static/OpenSans/OpenSans-Bold.ttf"
            icon: "home"
            on_tab_release:
                app.root.current = "menu"
                root.manager.transition.direction = "right"

            FitImage:
                source: "images/bg.png"